Django/22.09.27/실습/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('new/', views.new, name='new'),
    path('create/', views.create, name='create'),
    path('delete/<int:pk>', views.delete, name='delete'),
]

Django/22.09.27/실습/models.py
from django.db import models

# Create your models here.

class Post(models.Model):
    title = models.CharField(max_length=50)
    content = models.TextField()

Django/22.09.27/실습/views.py
from django.shortcuts import render, redirect
from .models import Post

# Create your views here.
def index(request):
    # 1. DB에서 모든 글을 불러온다.
    posts = Post.objects.all()

    context = {
        'posts' : posts,
    }

    # 2. template에 보내준다.
    return render(request, 'posts/index.html', context)

def new(request):
    return render(request, 'posts/new.html')

def create(request):
    title = request.GET.get('title')
    content = request.GET.get('content')

    Post.objects.create(title=title, content=content)
    
    context = {
        'title' : title,
        'content' : content,
    }

    return redirect('posts:index')

def delete(reqeust, pk):
    # pk에 해당하는 글 삭제
    Post.objects.get(id=pk).delete()

    return redirect('posts:index')

Django/22.09.27/실습/templates/posts/create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>작성 완료</h1>
    <p>제목: {{ title }}</p>
    <p>내용: {{ content }}</p>

    <a href="{% url 'posts:index'%}">목록으로</a>
</body>
</html>

Django/22.09.27/실습/templates/posts/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
<h1>게시판</h1>

<ul>
    {% for post in posts %}
    <li>ID: {{ post.id }} | 제목: {{ post.title }} | 내용: {{ post.content }} 
        <a href="">[수정]</a>
        <a href="/posts/delete/{{ post.id }}">[삭제]</a>
    </li>
    {% endfor %}
</ul>

<a href="{% url 'posts:new'%}">새글쓰기</a>
</body>
</html>

Django/22.09.27/실습/templates/posts/new.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>새글 쓰기</h1>
    <form action="{% url 'posts:create'%}">
        제목: <input type="text" name="title"><br>
        내용: <input type="text" name="content">
        <input type="submit">
    </form>
</body>
</html>